// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ejSYwBky9Cah1ezaX3fKlJ-TW0YHOKA',
    appId: '1:178342130980:web:1b82ae2760f4ceb303afb1',
    messagingSenderId: '178342130980',
    projectId: 'flutter-first-project-fc03a',
    authDomain: 'flutter-first-project-fc03a.firebaseapp.com',
    storageBucket: 'flutter-first-project-fc03a.appspot.com',
    measurementId: 'G-FLCM6R87HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdz_OcwZMFSv05UUsZM3OHjMNOL6T1V5k',
    appId: '1:178342130980:android:bb37833ca80c8fe403afb1',
    messagingSenderId: '178342130980',
    projectId: 'flutter-first-project-fc03a',
    storageBucket: 'flutter-first-project-fc03a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Jsd3A_GK9rcF7MWHzl_D8o5Gh2tVtW8',
    appId: '1:178342130980:ios:6a573bda9f355f7603afb1',
    messagingSenderId: '178342130980',
    projectId: 'flutter-first-project-fc03a',
    storageBucket: 'flutter-first-project-fc03a.appspot.com',
    iosClientId: '178342130980-ee8u9rjd9iqai8fjm3jgjbsm12b84ccm.apps.googleusercontent.com',
    iosBundleId: 'com.example.day1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4Jsd3A_GK9rcF7MWHzl_D8o5Gh2tVtW8',
    appId: '1:178342130980:ios:6a573bda9f355f7603afb1',
    messagingSenderId: '178342130980',
    projectId: 'flutter-first-project-fc03a',
    storageBucket: 'flutter-first-project-fc03a.appspot.com',
    iosClientId: '178342130980-ee8u9rjd9iqai8fjm3jgjbsm12b84ccm.apps.googleusercontent.com',
    iosBundleId: 'com.example.day1',
  );
}
